
export const Carddata = [
    {
        id: 1,
        imageUrl: '/App-Integration-page/stripe-icon.svg',
        companyName: 'Stripe',
        appCategory: 'Finance',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Atque aliquid provident necessitatibus vero, nobis in quis eos explicabo eveniet distinctio?',
    },
    {
        id: 2,
        imageUrl: '/App-Integration-page/gmail-tile.svg',
        companyName: 'Gmail',
        appCategory: 'Mails',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Atque aliquid provident necessitatibus vero, nobis in quis eos explicabo eveniet distinctio?'
    },
    {
        id: 3,
        imageUrl: '/App-Integration-page/google_ads-official.svg',
        companyName: 'Google Ads',
        appCategory: 'Publicity',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Atque aliquid provident necessitatibus vero, nobis in quis eos explicabo eveniet distinctio?',
    },
    {
        id: 4,
        imageUrl: '/App-Integration-page/dropbox-tile.svg',
        companyName: 'Dropbox',
        appCategory: 'Productivity',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Atque aliquid provident necessitatibus vero, nobis in quis eos explicabo eveniet distinctio?',
    },
    {
        id: 5,
        imageUrl: '/App-Integration-page/mailchimp-icon.svg',
        companyName: 'MailChimp',
        appCategory: 'Communication',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Atque aliquid provident necessitatibus vero, nobis in quis eos explicabo eveniet distinctio?',
    },
    {
        id: 6,
        imageUrl: '/App-Integration-page/slack-icon.svg',
        companyName: 'Slack',
        appCategory: 'Comunication',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Atque aliquid provident necessitatibus vero, nobis in quis eos explicabo eveniet distinctio?',
    },
    {
        id: 7,
        imageUrl: '/App-Integration-page/Google_Calendar_icon_(2020).svg',
        companyName: 'Google Calendar',
        appCategory: 'Productivity',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Atque aliquid provident necessitatibus vero, nobis in quis eos explicabo eveniet distinctio?',
    },
    {
        id: 8,
        imageUrl: '/App-Integration-page/notion-logo-svgrepo-com.svg',
        companyName: 'Notion',
        appCategory: 'Productivity',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Atque aliquid provident necessitatibus vero, nobis in quis eos explicabo eveniet distinctio?',
    },
    {
        id: 9,
        imageUrl: '/App-Integration-page/shopify-icon.svg',
        companyName: 'Shopify',
        appCategory: 'Productivity',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Atque aliquid provident necessitatibus vero, nobis in quis eos explicabo eveniet distinctio?',
    },
    {
        id: 10,
        imageUrl: '/App-Integration-page/woocommerce-icon-svgrepo-com.svg',
        companyName: 'WooCommerce',
        appCategory: 'Productivity',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Atque aliquid provident necessitatibus vero, nobis in quis eos explicabo eveniet distinctio?',
    },
    {
        id: 11,
        imageUrl: '/App-Integration-page/zendesk-svgrepo-com.svg',
        companyName: 'Zendesk',
        appCategory: 'Productivity',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Atque aliquid provident necessitatibus vero, nobis in quis eos explicabo eveniet distinctio?',
    },
    {
        id: 12,
        imageUrl: '/App-Integration-page/paypal-icon.svg',
        companyName: 'Paypal',
        appCategory: 'Finance',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Atque aliquid provident necessitatibus vero, nobis in quis eos explicabo eveniet distinctio?',
    },
    {
        id: 13,
        imageUrl: '/App-Integration-page/public/google-drive-svgrepo-com.svg',
        companyName: 'Google Drive',
        appCategory: 'File Management',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Atque aliquid provident necessitatibus vero, nobis in quis eos explicabo eveniet distinctio?',
    },
    {
        id: 14,
        imageUrl: '/App-Integration-page/dropbox-tile.svg',
        companyName: 'Terabox',
        appCategory: 'File Management',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Atque aliquid provident necessitatibus vero, nobis in quis eos explicabo eveniet distinctio?',
    },
    {
        id: 15,
        imageUrl: '/App-Integration-page/microsoft-outlook-svgrepo-com.svg',
        companyName: 'Microsoft Outlook',
        appCategory: 'Mails',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Atque aliquid provident necessitatibus vero, nobis in quis eos explicabo eveniet distinctio?',
    },
];
